### ISSUE TITLE
questions W3

### ISSUE THREAD

**Issue by muranyibence** [codingmentor/ugyfelnyilvantarto#110]
JMS:
Selector fix paraméterre, vagy hogy kell ezt értelmezni?
Alkalmazás web project, azaz mehetnek ide a listenerek is?

**Comment by andras-gyarmati** [comment]
ez az issue eltévedt vagy tőlünk kérdezed? :D

**Comment by muranyibence** [comment]
Eltévedt, bocsi. :D
Zárom
